### ISSUE TITLE
Notes from 2024-02-13

### ISSUE THREAD

**Issue by cmurray3** [IE-482-582/spring2024#11]
Reading for Thursday:
- Chapter 5 (Actions)
- Chapter 7 (Wander-bot)

**Comment by tallan232** [comment]
Professor,
Having trouble with ROS and Linux this morning.  Trying to follow tutorials online or in the book, causes problems in the Terminal - errors such as problems locating files and packages in my Linux directory, or unable to access certain items like Turtlebot (used in the book tutorial chapter 7), and other unknown errors. 

I can conceptualize the order of operations that the robot needs to follow for this assignment, but I'm not yet able to translate that into workable code at this point.  Do you have any recommendations as to a starting point to get us in the right direction?  I've been back and forth between your odom_subscriber code and cmd_vel code we looked at two weeks ago.
Thank you

**Comment by cmurray3** [comment]
> Having trouble with ROS and Linux this morning. Trying to follow tutorials online or in the book, causes problems in the Terminal - errors such as problems locating files and packages in my Linux directory, or unable to access certain items like Turtlebot (used in the book tutorial chapter 7), and other unknown errors.

Can you post the exact commands and error messages you're getting? 

> I can conceptualize the order of operations that the robot needs to follow for this assignment, but I'm not yet able to translate that into workable code at this point. Do you have any recommendations as to a starting point to get us in the right direction? I've been back and forth between your odom_subscriber code and cmd_vel code we looked at two weeks ago.

Sketching out the order of operations is a great start.  We will dive into detailed code writing in class tomorrow.  

In the meantime, I suggest breaking your code into small manageable chunks that serve a particular purpose.   I'm providing the class with some starter code to help with that process.  You can see the new code here:  https://github.com/IE-482-582/spring2024/pull/15/files

--- 
Using those helper functions, we can employ some logic like this:

In our odometry callback, we are saving variables describing our position/orientation:
```
self.pos_body_x_m = round( p.position.x, 3)
self.pos_body_y_m = round( p.position.y, 3)
self.heading = round(np.rad2deg(self.yaw), 1) 	
```
- These values will change over time.  We'll use the latest values in the code below.

Suppose we start at point (`self.pos_body_x_m`, `self.pos_body_y_m`), and that we want to travel along the `+x` direction a distance of `l` meters.  What are the coordinates of that goal/destination point?
```
[xGoal, yGoal] = getPointInDistXfwdDeg(self.pos_body_x_m, self.pos_body_y_m, 0, l)
```
- If we started at `[0,0]`, the result is `[10.0, 0.0]`

Now, we need to issue Twist commands to get our Husky to move to the goal.
It will be helpful if we know the following:
- a. What is the distance to the goal?
    ```
    distError = IE_tools.dist2target(xCur, yCur, xGoal, yGoal)
    # The result is 10.0
    ```
- b. Suppose we are currently rotated `+20` degrees (i.e., if `self.heading = 20`). How should we rotate to face the target/goal?
    ```
    (angleError, sign) = IE_tools.getLocalHeadingDeg(self.pos_body_x_m, self.pos_body_y_m, xGoal, yGoal, self.heading)
    # The result is (20, -1), which means we need to rotate 20 degrees in the (-) direction

So, given our distance to the goal, and the direction we need to rotate to correct course, we can issue a Twist command to move us closer to where we need to be.

Over time, `distError` should begin to shrink.  When it gets "close enough", we need to make a turn.
- Note:  There's a pattern of left/right turns along the long/short sides of the path.  We'll need to keep track of what action we're currently performing (and what's next).

Hopefully this gives you a head-start going into tomorrow's class.

**Comment by tallan232** [comment]
One thing I did was try to follow along with the wanderbot tutorial in the book, ch7.  I did ok until it came time to install the turtlebot; the error was "E: Unable to locate package ros-indigo-turtlebot-gazebo".  I tried to skip ahead and use husky instead of turtlebot, but I may be missing something else because nothing happened in Gazebo when I ran the program.

Next, I followed [this](https://www.clearpathrobotics.com/assets/guides/kinetic/ros/Drive%20a%20Husky.html) tutorial and was able to get the Husky to move by publishing linear.x commands to the cmd_vel topic like we did in class.

But I'm also having trouble connecting to github through VMware.  The internet connection seems fine, because I can navigate to Google and other websites on my virtual machine, but github is unreachable.  I don't think it's related to the settings we played with in class Thursday, because other websites load perfectly fine.  Using both Chrome and Firefox give me this error.  So I think my only option is to just copy and paste your github code into a new text doc in VM..?  I feel like there was an easier way in class.

Looking over your utility functions and your tips now, thank you.

**Comment by JackWuerfelUB** [comment]
Hello Professor,

I have a few questions.

1. I keep running into indentation errors while using visual studio code, do you recommend just using Geany? The errors are mainly from when trying to create new functions for a class.

2. For the husky zamboni node we are creating. I would like to utilize the IE_tools but "call" it into the the husky zamboni node. Referencing the code you posted "laser_scan_subscriber.py" you did the following:

import sys
sys.path.append("..")
import IE_tools.IE_tools as IE_tools

For it to work for me would I need to do something like this:
import sys
sys.path.append("/home/jack/Projects/IE-482-582/spring2024/Projects/IE_tools")
import IE_tools.IE_tools as IE_tools

or is there something different I'd need to do?

Thanks,
Jack

**Comment by cmurray3** [comment]
> 1. I keep running into indentation errors while using visual studio code, do you recommend just using Geany? The errors are mainly from when trying to create new functions for a class.

I haven't used VS Code much, but I suspect that the indentation issues might be fixable by changing your preferences.  Perhaps VS Code is trying to insert spaces (or tabs) by default, but you want tabs (or spaces).  I don't know that Geany will magically solve the indentation issues.  

You might search a little bit on "VS Code python indentation" and see if anyone else is describing a similar issue.

As a side note, I've just discovered that VS Code has some really powerful python formatting features:  https://code.visualstudio.com/docs/python/formatting 

> 2. For the husky zamboni node we are creating. I would like to utilize the IE_tools but "call" it into the the husky zamboni node. Referencing the code you posted "laser_scan_subscriber.py" you did the following:
> 
> ```
> import sys 
> sys.path.append("..") 
> import IE_tools.IE_tools as IE_tools
> ```
>
> For it to work for me would I need to do something like this: 
> ```
> import sys 
> sys.path.append("/home/jack/Projects/IE-482-582/spring2024/Projects/IE_tools")` 
> import IE_tools.IE_tools as IE_tools
> ```
> or is there something different I'd need to do?

Great question, and very close self-answer.  In the last line, just do `import IE_tools as IE_tools`

`sys.path.append` will tell Python where to look for code that you want to import. 
- The example in class (`sys.path.append("..")` simply told Python to look "up" one directory level.  Then, `import IE_tools.IE_tools as IE_tools` told Python that it needed to go into the `IE_tools` directory to find `IE_tools.py`.  
- A more general approach (your second one), is to append the entire path to a directory.  Note that you gave the entire path into the `IE_tools` directory, so you simply `import IE_tools as IE_tools`.

**However**, an even more general approach would be as follows:
```
import sys, os
sys.path.append(f"{os.environ['HOME']}/Projects/IE-482-582/spring2024/Projects/IE_tools")
import IE_tools as IE_tools
```
- `os.environ['HOME']` is an environment variable that captures the path to your home directory (in your case `/home/jack`).  The great thing about this approach is that you can share your code with someone else who has a different home directory and the code will still work!  If you hard-code the home directory, anyone who has a different home directory (i.e., not `/home/jack`) will have to edit the code before it will run.
    - NOTE:  `sys.path.append` doesn't like the `~` alias to your home directory.  So, `~/Projects/IE-482-582/spring2024/Projects/IE_tools` would not work.

**Comment by JackWuerfelUB** [comment]
Hi Professor,

Any tips for the following error?:
AttributeError: 'Zamboni' object has no attribute 'pos_body_x_m'

Some background: 
pos_body_x_m is initialized in the callback_odometry function and I am referencing it quite a few times in my run function. Every time I "call" it I have the "self." prefix on it.

The entire error message, if useful:
Traceback (most recent call last):
  File "zamboni_JRW_geany.py", line 216, in <module>
    Zamboni()
  File "zamboni_JRW_geany.py", line 86, in __init__
    self.run()
  File "zamboni_JRW_geany.py", line 144, in run
    while IE_tools.dist2target(self.pos_body_x_m, self.pos_body_y_m, x_goal, y_goal) > LINEAR_X_ERROR_MARGIN: #go forward if not reached target
AttributeError: 'Zamboni' object has no attribute 'pos_body_x_m'

Thanks,
Jack

**Comment by cmurray3** [comment]
Jack, My guess is that the code in your `while` loop is executing before the `callback_odometry` function is called.  This is pretty common when you have two things running in parallel (asynchronously).  

The standard "fix" for this issue is to initialize such variables inside `def __init__(self)`.  You could assign `self.pos_body_x_m` to a value of `0`, for example.  Then, if your `while` loop references this variable before it gets updated with an **actual** value in the odom callback, at least Python won't complain about an undefined variable.

**However, this is a little dangerous** (assigning the position to be 0), since you really don't know where the Husky actually is!

So, **a safer approach** would be:
- In the `__init__` function, assign the variables to a `None` value:
    ```
    self.pos_body_x_m = None
    self.pos_body_y_m = None
    self.heading = None
    ```
- Before calling the `run` function , add a `while` loop (this would go inside `__init__`) that waits for those variables to be set.:
    ```
    while ((self.pos_body_x_m is None) or  (self.pos_body_y_m is None) or  (self.heading is None)):
        print('waiting for the odom callback to provide real values for these variables...')
        time.sleep(1)   # We use the Python `sleep` function here because we don't care about a specific run rate.
    ```
    - Note:  To use `time.sleep`, add `import time` to the top of your `.py` script.
    - As soon as all 3 of these variables have been assigned, this `while` loop will end and your code can continue on to call `self.run()`.
