### ISSUE TITLE
Node.JS error

### ISSUE THREAD

**Issue by BrainFog2** [IE-482-582/spring2024#48]
--(Node.JS Tab) In the Node.js tab the following is read:

/home/student/catkin_ws/src/ub_web/html/node_modules/yargs-parser/build/index.cjs:1015
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/home/student/catkin_ws/src/ub_web/html/node_modules/yargs-parser/build/index.cjs:1015:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/student/catkin_ws/src/ub_web/html/node_modules/yargs/build/index.cjs:1:59931)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

--(UB_web launch tab) UB_web/launch seems good with the following:

.. logging to /home/student/.ros/log/ddb8b14e-fc04-11ee-9db7-1f6f3769afbf/roslaunch-ubuntu-13049.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:40277/

SUMMARY
========

PARAMETERS
 * /rosapi/params_glob: [*]
 * /rosapi/services_glob: [*]
 * /rosapi/topics_glob: [*]
 * /rosbridge_websocket/address: 0.0.0.0
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/certfile: /home/student/cat...
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/keyfile: /home/student/cat...
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/params_glob: [*]
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosbridge_websocket/services_glob: [*]
 * /rosbridge_websocket/topics_glob: [*]
 * /rosbridge_websocket/unregister_timeout: 99999999
 * /rosbridge_websocket/use_compression: False
 * /rosbridge_websocket/websocket_external_port: None
 * /rosbridge_websocket/websocket_null_origin: True
 * /rosbridge_websocket/websocket_ping_interval: 0
 * /rosbridge_websocket/websocket_ping_timeout: 30
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)

ROS_MASTER_URI=http://localhost:11311

process[rosbridge_websocket-1]: started with pid [13111]
process[rosapi-2]: started with pid [13112]
[INFO] [1713280857.665658, 1315.950000]: Rosapi started
2024-04-16 11:20:57-0400 [-] Log opened.
2024-04-16 11:20:58-0400 [-] registered capabilities (classes):
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.call_service.CallService'>
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.advertise.Advertise'>
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.publish.Publish'>
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.subscribe.Subscribe'>
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.advertise_service.AdvertiseService'>
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.service_response.ServiceResponse'>
2024-04-16 11:20:58-0400 [-]  - <class 'rosbridge_library.capabilities.unadvertise_service.UnadvertiseService'>
2024-04-16 11:20:58-0400 [-] WebSocketServerFactory (TLS) starting on 9090
2024-04-16 11:20:58-0400 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7ff6850aab80>
2024-04-16 11:20:58-0400 [-] [INFO] [1713280858.450418, 0.000000]: Rosbridge WebSocket server started at wss://0.0.0.0:9090

--(Main.py tab) The Following is in Main.py:

robotID: 0
severity: 3
text: "Error in subscribing to audio_command: name 'MAV_SEVERITY_ERROR' is not defined"
userID: 0
speakMsg: ''

**Comment by Huize-Hou** [comment]
I got another error on Main.Py

/home/hh/.local/lib/python3.8/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xd . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
robotID: 0
severity: 3
text: "Error in subscribing to audio_command: name 'MAV_SEVERITY_ERROR' is not defined"
userID: 0
speakMsg: ''

**Comment by cmurray3** [comment]
For those who were getting the `Error: yargs parser supports a minimum Node.js version of 12. Read our version support policy...` error, can you tell me what you're getting as outputs from the following two commands?

```
node -v
```

```
npm -v
```

---

Regarding the errors associated with `MAV_SEVERITY_ERROR`, I have updated the `ub_web` repo with a fix.  Here's how to get the latest code:
```
cd ~/catkin_ws/src/ub_web
git pull origin master
```

**Comment by cmurray3** [comment]
Try to install from here:
https://nodejs.org/en/download/package-manager
